# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130aL2gtHFk0-iHSUOttNLaF5PFCsS00K

### Question_1

Write a code example using len() to find the length of a list.Python-Functions What does the len() function do in Python?
"""

List = [10, 20, 30, 40, 50]
length = len(List)
print("The length of the list is:", length)

"""The len() function in Python is used to determine the number of elements in an iterable (such as a list, string, tuple, dictionary, or set).

### Question _2

Write a Python function greet(name) that takes a person's name as input and prints "Hello, [name]!".
"""

name = "noufal"
def greet(name):
  print("Hello, " + name + "!")
greet("Noufal")

"""### Question_3

Write a Python function find_maximum(numbers) that takes a list of integers and returns the maximum value without using the built-in max() function.
"""

def find_maximum(numbers):
    max_value = numbers[0]
    for num in numbers:
        if num > max_value:
            max_value = num
    return max_value

numbers = [3, 7, 2, 9, 5]
print("Maximum value:", find_maximum(numbers))

"""### Question_4

Explain the difference between local and global variables in a Python function.

A global variable is declared outside any function and is accessible throughout the program.
A local variable is declared inside a function and only exists within that function.

Explain the difference between local and global variables in a Python function.
"""

value = 50

def my_function():

    value = 75
    print("Inside the function, local value:", value)

my_function()

print("Outside the function, global value:", value)

"""### Qusetion_5

Create a function calculate_area(length, width=5) that calculates the area of a rectangle. If only the length is provided, the function should assume the width is 5. Show how the function behaves when called with and without the width argument.
"""

def calculate_area(length, width=5):
    """Calculate the area of a rectangle."""
    return length * width
area_1 = calculate_area(10, 7)
print("Area when both length and width are provided:", area_1)

area_2 = calculate_area(10)
print("Area when only length is provided:", area_2)