# -*- coding: utf-8 -*-
"""Python_Part_Assignment_OOPs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mo8VUOwotNlRmtrbG9E73jN6TG99Pf9C

Build a program to manage a university's course catalog.
"""

class Course:
    def __init__(self, course_code, course_name, credit_hours):
        self.course_code = course_code
        self.course_name = course_name
        self.credit_hours = credit_hours

    def display_info(self):
        return f"Course Code: {self.course_code}, Course Name: {self.course_name}, Credit Hours: {self.credit_hours}"


class CoreCourse(Course):
    def __init__(self, course_code, course_name, credit_hours, required_for_major):
        super().__init__(course_code, course_name, credit_hours)
        self.required_for_major = required_for_major

    def display_info(self):
        core_status = "Required" if self.required_for_major else "Optional"
        return super().display_info() + f", Required for Major: {core_status}"


class ElectiveCourse(Course):
    def __init__(self, course_code, course_name, credit_hours, elective_type):
        super().__init__(course_code, course_name, credit_hours)
        self.elective_type = elective_type

    def display_info(self):
        return super().display_info() + f", Elective Type: {self.elective_type}"

core = CoreCourse("CS101", "Introduction to Computer Science", 3, True)
elective = ElectiveCourse("HIST201", "World History", 3, "liberal arts")

print(core.display_info())
print(elective.display_info())

"""Create a Python module named employee that contains a class Employee with attributes name, salary and methods get_name() and get_salary(). Write a program to use this module to create an object of the Employee class and display its name and salary.

"""

# employee.py

with open("employee.py", "w") as f:
    f.write('''
class Employee:
    def __init__(self, name, salary):
        self.__name = name
        self.__salary = salary

    def get_name(self):
        return self.__name

    def get_salary(self):
        return self.__salary
''')

import employee

# Create an Employee object
emp = employee.Employee("NOUFAL", 50000)

print("Employee Name:", emp.get_name())
print("Employee Salary:", emp.get_salary())