# -*- coding: utf-8 -*-
"""Assignment_7-Numpy_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16hZ-vpPkD707c3ZFIu8L9mpCZcliySDX

Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.
"""

import numpy as np
arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)
print(matrix)

"""Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index"""

import numpy as np
arr = np.arange(1, 21)
extracted = arr[5:16]

print("Original Array:", arr)
print("Extracted Elements (5th to 15th index):", extracted)

"""Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


"""

import pandas as pd

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

fruit_series['pears'] = 4

print(fruit_series)

"""Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

"""

import pandas as pd
import numpy as np

data = {
    'name': ['Noufal', 'Anwar', 'Suhail', 'Rajesh', 'Noufidha', 'Ali', 'Aman', 'Haris', 'Sumayya', 'Sinsiya'],
    'age': np.random.randint(18, 65, 10),
    'gender': np.random.choice(['Male', 'Female', 'Other'], 10)
}

df = pd.DataFrame(data)

print(df)

"""Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe."""

df = pd.DataFrame(data)

occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

df['occupation'] = occupations

print(df)

"""Select the rows of the dataframe where the age is greater than or equal to 30.

"""

df = pd.DataFrame(data)

older_than_30 = df[df['age'] >= 30]

print(older_than_30)

"""Convert this dataframe to a csv file and read that csv file, finally display the contents.

"""

df = pd.DataFrame(data)

import io

csv_buffer = io.StringIO()
df.to_csv(csv_buffer, index=False)
csv_buffer.seek(0)


df_from_csv = pd.read_csv(csv_buffer)


print(df_from_csv)